/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as ElencoRouteImport } from './routes/elenco'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTimeIndexRouteImport } from './routes/admin.time.index'
import { Route as AdminJogosIndexRouteImport } from './routes/admin.jogos.index'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const ElencoRoute = ElencoRouteImport.update({
  id: '/elenco',
  path: '/elenco',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimeIndexRoute = AdminTimeIndexRouteImport.update({
  id: '/admin/time/',
  path: '/admin/time/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJogosIndexRoute = AdminJogosIndexRouteImport.update({
  id: '/admin/jogos/',
  path: '/admin/jogos/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elenco': typeof ElencoRoute
  '/jogos': typeof JogosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/jogos/': typeof AdminJogosIndexRoute
  '/admin/time/': typeof AdminTimeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elenco': typeof ElencoRoute
  '/jogos': typeof JogosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/admin': typeof AdminIndexRoute
  '/admin/jogos': typeof AdminJogosIndexRoute
  '/admin/time': typeof AdminTimeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elenco': typeof ElencoRoute
  '/jogos': typeof JogosRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/jogos/': typeof AdminJogosIndexRoute
  '/admin/time/': typeof AdminTimeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/elenco'
    | '/jogos'
    | '/login'
    | '/perfil'
    | '/ranking'
    | '/admin/'
    | '/admin/jogos/'
    | '/admin/time/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/elenco'
    | '/jogos'
    | '/login'
    | '/perfil'
    | '/ranking'
    | '/admin'
    | '/admin/jogos'
    | '/admin/time'
  id:
    | '__root__'
    | '/'
    | '/elenco'
    | '/jogos'
    | '/login'
    | '/perfil'
    | '/ranking'
    | '/admin/'
    | '/admin/jogos/'
    | '/admin/time/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElencoRoute: typeof ElencoRoute
  JogosRoute: typeof JogosRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminJogosIndexRoute: typeof AdminJogosIndexRoute
  AdminTimeIndexRoute: typeof AdminTimeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elenco': {
      id: '/elenco'
      path: '/elenco'
      fullPath: '/elenco'
      preLoaderRoute: typeof ElencoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/time/': {
      id: '/admin/time/'
      path: '/admin/time'
      fullPath: '/admin/time/'
      preLoaderRoute: typeof AdminTimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jogos/': {
      id: '/admin/jogos/'
      path: '/admin/jogos'
      fullPath: '/admin/jogos/'
      preLoaderRoute: typeof AdminJogosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElencoRoute: ElencoRoute,
  JogosRoute: JogosRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminJogosIndexRoute: AdminJogosIndexRoute,
  AdminTimeIndexRoute: AdminTimeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
